# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gluon_arm_controller

  gluon_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - axis_joint_1
      - axis_joint_2
      - axis_joint_3
      - axis_joint_4
      - axis_joint_5
      - axis_joint_6