bool is_lookup
---
int32 cur_iq_setting 
int32 cur_proportional 
int32 cur_integral      
int32 cur_id_setting    
int32 cur_maxspeed      
int32 actual_current    
int32 vel_setting       
int32 vel_proportional  
int32 vel_integral      
int32 vel_output_limitation_minimum  
int32 vel_output_limitation_maximum  
int32 actual_velocity 
int32 pos_setting  
int32 pos_proportional 
int32 pos_integral 
int32 pos_differential 
int32 pos_output_limitation_minimum 
int32 pos_output_limitation_maximum 
int32 pos_limitation_minimum 
int32 pos_limitation_maximum 
int32 homing_position 
int32 actual_position 
int32 profile_pos_max_speed 
int32 profile_pos_acc 
int32 profile_pos_dec 
int32 profile_vel_max_speed 
int32 profile_vel_acc 
int32 profile_vel_dec 
int32 pos_offset 
int32 voltage 
int32 pos_limitation_switch 
int32 current_scale  
int32 velocity_scale 
int32 filter_c_status 
int32 filter_c_value  
int32 filter_v_status 
int32 filter_v_value  
int32 filter_p_status 
int32 filter_p_value  
int32 lock_energy 
int32 actuator_temperature 
int32 inverter_temperature 
int32 actuator_protect_temperature   
int32 actuator_recovery_temperature  
int32 inverter_protect_temperature   
int32 inverter_recovery_temperature  
int32 actuator_switch  
int32 firmware_version 
int32 online_status